//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.5448
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMP.FMP7 {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FMP7ApiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FMP7ApiResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FMP.FMP7.FMP7ApiResource", typeof(FMP7ApiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   FMP7はwaveファイル出力によりロックされています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsg_Busy {
            get {
                return ResourceManager.GetString("ErrMsg_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大ワークサイズをオーバーしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsg_CopySizeOver {
            get {
                return ResourceManager.GetString("ErrMsg_CopySizeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定演奏ドライバは未起動です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsg_DriverNotReady {
            get {
                return ResourceManager.GetString("ErrMsg_DriverNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル読み込みに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsg_FileLoad {
            get {
                return ResourceManager.GetString("ErrMsg_FileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OWIデータではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsg_FileNoOWI {
            get {
                return ResourceManager.GetString("ErrMsg_FileNoOWI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未対応の演奏データです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsg_FileNoSupport {
            get {
                return ResourceManager.GetString("ErrMsg_FileNoSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不明な入出力エラーです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsg_FileUnknowns {
            get {
                return ResourceManager.GetString("ErrMsg_FileUnknowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FMP7が見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsg_FMPNotFound {
            get {
                return ResourceManager.GetString("ErrMsg_FMPNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsg_NonError {
            get {
                return ResourceManager.GetString("ErrMsg_NonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   非対応バージョンのFMPが起動しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsg_NotSupportedFMPVersion {
            get {
                return ResourceManager.GetString("ErrMsg_NotSupportedFMPVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   呼び出し元プロセスアクセスエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsg_OpenProc {
            get {
                return ResourceManager.GetString("ErrMsg_OpenProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータ指定範囲が間違っています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsg_ParamRange {
            get {
                return ResourceManager.GetString("ErrMsg_ParamRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パート番号指定が間違っています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsg_PartRange {
            get {
                return ResourceManager.GetString("ErrMsg_PartRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモリ読み込みエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsg_ReadMemory {
            get {
                return ResourceManager.GetString("ErrMsg_ReadMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   シーク指定範囲が間違っています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsg_SeekRange {
            get {
                return ResourceManager.GetString("ErrMsg_SeekRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワークサイズが合いません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsg_WorkSizeNoMatch {
            get {
                return ResourceManager.GetString("ErrMsg_WorkSizeNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   格納ワークサイズが小さいです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsg_WorkSizeShort {
            get {
                return ResourceManager.GetString("ErrMsg_WorkSizeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモリ書き込みエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrMsg_WriteMemory {
            get {
                return ResourceManager.GetString("ErrMsg_WriteMemory", resourceCulture);
            }
        }
    }
}
